### ISSUE TITLE
Uncaught DOMException: Failed to execute 'postMessage' on 'Worker': An object could not be cloned

### ISSUE THREAD

**Issue by sulhadin** [alewin/useWorker#85]
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Worker': capacityList => {
  console.log(capacityList);
  const capacityMap = {
    Total: {}
  };
  let i = 0;

  for (...<omitted>...
} could not be cloned.
    at http://localhost:8089/js/modules/npm.koale.bundle-1600196980210.js:16:3150
    at new Promise (<anonymous>)
    at http://localhost:8089/js/modules/npm.koale.bundle-1600196980210.js:16:2782
    at http://localhost:8089/js/modules/npm.koale.bundle-1600196980210.js:16:3619
    at runReport (http://localhost:8089/js/app.bundle-1600196980210.js:54075:26)
    at http://localhost:8089/js/app.bundle-1600196980210.js:54105:5
    at commitHookEffectListMount (http://localhost:8089/js/modules/npm.react-dom.bundle-1600196980210.js:23796:26)
    at commitPassiveHookEffects (http://localhost:8089/js/modules/npm.react-dom.bundle-1600196980210.js:23834:11)
    at HTMLUnknownElement.callCallback (http://localhost:8089/js/modules/npm.react-dom.bundle-1600196980210.js:4253:14)
    at Object.invokeGuardedCallbackDev (http://localhost:8089/js/modules/npm.react-dom.bundle-1600196980210.js:4302:16)
    at invokeGuardedCallback (http://localhost:8089/js/modules/npm.react-dom.bundle-1600196980210.js:4357:31)
    at flushPassiveEffectsImpl (http://localhost:8089/js/modules/npm.react-dom.bundle-1600196980210.js:26918:9)
    at unstable_runWithPriority (http://localhost:8089/js/modules/npm.scheduler.bundle-1600196980210.js:1024:12)
    at runWithPriority$1 (http://localhost:8089/js/modules/npm.react-dom.bundle-1600196980210.js:15104:10)
    at flushPassiveEffects (http://localhost:8089/js/modules/npm.react-dom.bundle-1600196980210.js:26885:12)
    at performSyncWorkOnRoot (http://localhost:8089/js/modules/npm.react-dom.bundle-1600196980210.js:25802:3)

**Comment by gonzachr** [comment]
Hi! Thanks for reporting.

Can you share your code or a minimal reproduction in a CodeSandbox or repo for us to take a look?

**Comment by Kaywee27** [comment]
@zant 
Any update on this?

**Comment by gondar00** [comment]
Facing same issue

**Comment by laphilosophia** [comment]
any news?

**Comment by willh33** [comment]
Hitting the same thing

**Comment by QC2168** [comment]
I have same problem

**Comment by aurelien-boubennec** [comment]
Same issue

**Comment by menasheh** [comment]
Experiencing same issue, this happens when passing a function to the worker

**Comment by Reg011** [comment]
Same issue here
